### ISSUE TITLE
"Share on Tweetdeck" contextual menu not working

### ISSUE THREAD

**Issue by plissken1138** [dimdenGD/BetterTweetDeck#15]
**Describe the bug**
"Share on Tweetdeck" contextual menu not working. Permission to access tabs granted on add-on install. Tried reinstalling the add-on, no go. The menu item is there, but does not do anything when clicked.

**Expected behavior**
"Share on Tweetdeck" contextual menu to place selected text/link into Tweet composer ready to post.

- Win10Edu 22H2 x64
- Firefox Developer
- Version 123.0b9 (64-bit)

**Comment by WalsGit** [comment]
I fixed it here https://github.com/dimdenGD/BetterTweetDeck/pull/11, it was merged then, but after the subsequent version releases, the fix didn't seem to carry over. (it's a simple fix too, it's just a url change)

**Comment by WalsGit** [comment]
after digging a bit, that fix wasn't working anymore because the app moved from twitter.com to x.com so I made a new PR to fix this https://github.com/dimdenGD/BetterTweetDeck/pull/26

**Comment by plissken1138** [comment]
I can't get it to work. Enabling and reloading the tab didn't work. It did not ask for permission, so I checked and the permission setting was already enabled in extension settings. So I did reset both serttings, reloaded tab, enabled Contextual menu setting again, this time it did ask for permission, but it still doesn't work, either for sellected text or links.

Latest developer, latest BTD.

**Comment by WalsGit** [comment]
@dimdenGD merged my fix but didn't issue a new release yet, so if you're trying with the 4.11.3 version of BTD it won't work.
